# Generated by Django 6.0.4 on 2026-05-05 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('USER_CREATED', 'Usuario creado'), ('USER_UPDATED', 'Usuario actualizado'), ('USER_DELETED', 'Usuario eliminado'), ('TANK_CREATED', 'Tanque creado'), ('TANK_DELETED', 'Tanque eliminado'), ('DEVICE_ONLINE', 'Dispositivo conectado'), ('DEVICE_OFFLINE', 'Dispositivo desconectado'), ('LOGIN_SUCCESS', 'Inicio de sesión exitoso'), ('LOGIN_FAILED', 'Intento de sesión fallido'), ('SYSTEM', 'Evento del sistema')], max_length=30)),
                ('level', models.CharField(choices=[('INFO', 'Información'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('SUCCESS', 'Éxito')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
